.TH FCC 1 fcc
.SH NAME
fcc \- fiscal code checker
.SH DESCRIPTION
Checks if a given fiscal code is valid by calculating its check digit.
.SH SYNOPSIS
.BR fcc " "
<fiscal code>
.SH EXIT CODES
.IP 0
All went fine. Code gets passed to stdout in lowercase.
.PP
.IP 1
Bad parameters: this program accepts only one parameter.
.PP
.IP 2
Bad code: it should be 16 digits long and have 8 letters.
.PP
.IP 3
Bad check digit: it's mispelled.
.PP
.SH AUTHOR
(c) Emanuele Lillo <ecl@tfwno.gf>
